name: Release candidates

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install arm-none-eabi-g++
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-arm-none-eabi
          version: 1.3

      - name: Set up PROS
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install pros-cli


      - name: Build
        run: make template

      - name: Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ReveilLib ${{ github.ref }}
          draft: false
          prerelease: true