name: Releases

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: okapilib/ubuntu-base:18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: apt -y install software-properties-common
      - run: add-apt-repository ppa:team-gcc-arm-embedded/ppa && apt update
      - run: apt -y install make build-essential python3 python3-pip gcc-arm-embedded
      - run: python3 -m pip install https://github.com/purduesigbots/pros-cli/releases/download/3.1.4/pros_cli_v5-3.1.4-py3-none-any.whl


      - name: Build
        run: make template

      - name: Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ReveilLib ${{ github.ref }}
          draft: false
          prerelease: false