name: Releases

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: okapilib/ubuntu-base:22.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install arm-none-eabi-g++
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc-arm-none-eabi


      - name: Build
        run: make template

      - name: Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ReveilLib ${{ github.ref }}
          draft: false
          prerelease: false